name: CI

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node: [12, 14, lts/*]
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node }}
      - name: Cache node_modules
        uses: actions/cache@v2
        with:
          path: '**/node_modules'
          key: ${{ runner.os }}-modules-v${{ matrix.node }}-${{ hashFiles('**/yarn.lock') }}
      - name: Install dependencies
        run: yarn install
      - name: Lerna bootstrap
        run: yarn lerna bootstrap

      - name: Build
        run: yarn lerna run build

      - name: Lint
        run: yarn lint

      - name: Test
        run: yarn test

      - name: Codecov report upload
        if: ${{ matrix.node }} == 'lts/*'
        run: |
          npm install -g codecov
          ./scripts/codecov.sh

      - name: NPM Publish
        if: github.event_name == 'push' && contains(github.ref, 'refs/tags/')
        id: publish
        uses: JS-DevTools/npm-publish@v1
        with:
          token: TODO:${{ secrets.NPM_TOKEN }}
          check-version: true
          dry-run: true
